### ISSUE TITLE
Update to Allow Watchmaker to Exit Safely Even if Salt Doesn't

### ISSUE THREAD

**Issue by KevinPlus3** [plus3it/watchmaker#84] opened 2016-10-28 20:23 UTC

**Comment by KevinPlus3** [comment] 2016-12-06 18:42
Need to explore how to do this, while we want to exit safely from Watchmaker, we do not want to produce a "success" response, but rather pass along the failure of Salt.  First ... need to explore Watchmaker's runs versus SystemPrep to ensure they both produce the same results.

**Comment by lorengordon** [comment] 2017-02-06 21:16
Does anyone have a reproducible use case for this one? Or more details around what the problem was? I'm drawing a blank...

**Comment by KevinPlus3** [comment] 2017-02-07 01:57
It was an issue that usually popped up if the Salt command itself was returning a non-zero response.  This caused Watchmaker to fail instead of exiting smoothly and returning a non-zero response itself.

It may be that we want it to act that way - I was thinking we might want Watchmaker to properly close up the worker cadence and then exit with a non-zero response - informing the user that Salt was producing errors.

**Comment by lorengordon** [comment] 2017-02-07 13:54
Ok, so maybe a try/except block around the call to the worker. I'll think about that as I work #110.

**Comment by lorengordon** [comment] 2017-02-07 21:42
I think some of the other cli work must have addressed this. If I force an error in the salt execution, it is raised to `watchmaker.Client.install()`, a message is logged, and watchmaker exits non-zero. Gonna close this.

**Closed by lorengordon** 2017-02-07 21:42 UTC
