### ISSUE TITLE
Hostnames resetting in linux 7

### ISSUE THREAD

**Issue by Vandalay1125** [plus3it/watchmaker#761] opened 2019-01-30 14:16 UTC
Robert Fink HS (rfink@fearless.tech) reports hostnames on linux resetting from the one specified during provisioning with Watchmaker back to a DHCP determined name later in the life of the instance after a reboot. He points to this article (https://aws.amazon.com/premiumsupport/knowledge-center/linux-static-hostname-rhel7-centos7/) and says we need **-static** when invoking hostnamectl and to set **preserve_hostname: True** in **/etc/cloud/cloud.cfg** to prevent this.

**Comment by ferricoxide** [comment] 2019-01-30 14:54
Issue is already being tracked internally. 

The watchmaker-related hostname-setting actually happens as part of the [PBIS-specific domain-join](https://github.com/plus3it/join-domain-formula/blob/master/join-domain/elx/pbis/files/join.sh) functionality. Unfortunately, this means we're not using `hostnamectl` for name-setting, and, by extension, any flags for that command are not germane.

The "DHCP-set hostname is too persistent" issue cropped up due to Red Hat having re-based the version of `cloud-init` included in 7.6 (and presumably onward ...though there may be _further_ rebasing meaning this may be a problem that we have to "chase" depending on vendor-activities). Persistency via `cloud-init` will need to be traced-out.

Note that this issue does _not_ effect systems where hostnames are set using:

~~~
#cloud-config 

hostname: <HOSTNAME>
~~~

In the instance/LaunchConfig's UserData. Offering the above as a work-around till the issue is isolated and more-broadly "fixed" (in whichever project or module proves most suitable: likely in AMIgen or elsewhere &mdash; in which case _this_ issue will be closed and a pointer to the new issue will be left a a further comment).

**Comment by lorengordon** [comment] 2019-01-30 22:11
The domain-join formula will only apply a computername if the current name is longer than the max 15 chars supported by Active Directory.

The [name-computer formula](https://github.com/plus3it/name-computer-formula) is what applies the user-specified computername, and typically it is executed before the domain-join.

`--static` doesn't really appear necessary, as far as I can tell. That is restricting the behavior of hostnamectl, but is not modifying anything that would otherwise affect the non-persistent name behavior (which looks to be caused by cloud-init).

We could probably deal with the OP issue in the name-computer formula, detecting if /etc/cloud/cloud.cfg is present and if so writing either the `hostname` or `preserve_hostname` options.

**Comment by lorengordon** [comment] 2019-01-30 22:34
I'm guessing it's this [`update_hostname`](https://github.com/cloud-init/cloud-init/blob/master/cloudinit/config/cc_update_hostname.py) module from cloud-init that is really causing the problem, as its frequency is ALWAYS.

The [`set_hostname`](https://github.com/cloud-init/cloud-init/blob/master/cloudinit/config/cc_set_hostname.py) module should only be executing _once_, and _before_ watchmaker has salt runs its own hostname function (so watchmaker should "win" that battle).

Here's the cloud-init function that is actually getting the hostname... You can see it is pulling it from metadata (when other conditions are not met).

* https://github.com/cloud-init/cloud-init/blob/master/cloudinit/util.py#L1085-L1113

**Comment by ferricoxide** [comment] 2019-01-30 22:35
> `--static` doesn't really appear necessary, as far as I can tell. That is restricting the behavior of hostnamectl, but is not modifying anything that would otherwise affect the non-persistent name behavior (which looks to be caused by cloud-init).

Default behavior for `hostnamectl` is to set both the "temporary" _and_ persistent hostname.  Per the `man` page:

> `By default, this will alter the pretty, the static, and the transient hostname alike; however, if one or more of --static, --transient, --pretty are used, only the selected hostnames are changed.`

Passing `--static` only affects the name that will be used post-reboot. So, less not being "necessary" but more  "likely something we _don't_ want to do" (since the `transient` hostname &mdash; i.e., the hostname of the current epoch &mdash; would remain unchanged and would potentially cause further breakage elsewhere).

**Comment by ferricoxide** [comment] 2019-01-31 20:37
Euw... That's _ugly_. It's _looking like_, if we were habitually passing in FQDNs (rather than Windows-style shortnames), it would never reach that third-level "do I need to pull from instance metadata" section?

I so frequently put `hostname: { "Ref": "WatchmakerComputerName" }` in my templates that I assumed that _that_ was preventing the problem ...but it looks like it may be more that I generally select FQDN as the value for my `WatchmakerComputerName` value.

Just for shits-n-grins (i.e., until the 8th when I _should_ be done with the current project), can someone try deploying and settting `WatchmakerComputerName` to FQDN and see if continues to get overridden? That should help identfy where/why that third-level condition is the one getting triggered.

**Comment by ferricoxide** [comment] 2019-02-08 17:22
Note:

To date, issue hasn't been reproducible in our primary testing environment using the January 2019 AMI:
* Tested using a generic `hostnamectl set-hostname <FQDN>`  via UserData in a `#!/bin/bash` block
* Tested using a generic `hostnamectl set-hostname <NODE_NAME>`  via UserData in a `#!/bin/bash` block
* WAM with default config
* WAM with site-config (main lab's)

First two bullets would seem to indicate "not a problem with `cloud init`" (at least not when used in the us-east-1 region and/or with the one in the January 2019 AMI) and how it handles FQDN vs. short-name. Second two bullets would seem to indicated "not a problem inherent to `watchmaker`  (at least not when used in the us-east-1 region and/or with the one in the January 2019 AMI).

Going to need assistance reproducing the issue. Will need to know:
- Region(s)/partition(s) effected
- AMI ID(s) that have produced the observed bug
- WAM profile(s) selected when issue appeared
- log-files uploaded to a suitable location for viewing

**Comment by ferricoxide** [comment] 2019-02-11 16:23
Just did some further testing, this morning:

* June 2018 AMI — problem is reproducible
* January 2019 AMI — problem is _not_ reproducible

At this point, I'm assuming that this may be a watchmaker/EL7.5 compatibility issue, but am going to test against other AMIs (between the above-listed releases) to see if it's an AMI-by-AMI issue or if it's a 7.5 vs 7.6 issue.

**Comment by ferricoxide** [comment] 2019-02-11 17:40
Just validated that it's an issue with 7.5. Tested all AMIs from May 2018 through January 2019. The CentOS 7.5 AMIs (May through November 2018) all exhibited the issue. The CentOS 7.6 AMIs (December 2018 and January 2019) did _not_ display the issue.

Given the general guidance to "always use latest available spel AMI", any fixes would be low-priority (and only serve to encourage spel-users to use old AMIs).

**Comment by ferricoxide** [comment] 2019-02-12 16:12
Closing.

**Closed** 2019-02-12 16:13 UTC
Labels: bug - backwards compatibility, low-pri
